Integrate new diagram-js canvas - focus on canvas after editing
bpmn-io/diagram-js-direct-editing pull request #49
Opened 2024-10-18 14:34 UTC by jarekdanielak

Related to https://github.com/bpmn-io/diagram-js/issues/661

### Proposed Changes

Refocus back on canvas on close. 

 

### Checklist

To ensure you provided everything we need to look at your PR:

* [x] **Brief textual description** of the changes present
* [ ] **Visual demo** attached
* [ ] **Steps to try out** present, i.e. [using the `@bpmn-io/sr` tool](https://github.com/bpmn-io/sr)
* [x] Related issue linked via `Closes {LINK_TO_ISSUE}` or `Related to {LINK_TO_ISSUE}`

2024-11-04 15:01 UTC, jarekdanielak commented
@nikku this is now ready for review since `diagram-js@15.0.0` is released.

2024-11-04 15:50 UTC, nikku commented on lib/DirectEditing.js
> +  this._canvas.restoreFocus();
Consider the upgrade path. This breaks with `diagram-js <= 15`.

2024-11-04 15:51 UTC, nikku requested changes
Not backwards compatible. Fine if we release this as a major.

However, as we mark `diagram-js: *` [as a peer dependency](https://github.com/bpmn-io/diagram-js-direct-editing/pull/49/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R50) I'd rather gracefully handle `Canvas#restoreFocus` not being there.

2024-11-04 17:25 UTC, jarekdanielak commented
Great point about backwards compatibility.

I added a safety check.

2024-11-04 19:58 UTC, nikku commented on lib/DirectEditing.js
> +  // restoreFocus API is available from diagram-js@15.0.0
What about adding an integration test, verifying this continues to work with diagram-js@14?

2024-11-04 19:58 UTC, nikku commented on lib/DirectEditing.js
> +  // restoreFocus API is available from diagram-js@15.0.0
Playbook here: https://github.com/bpmn-io/bpmn-js-properties-panel/blob/main/.github/workflows/CI.yml

(Basically execute the tests twice, once with normal dependency, once against defined diagram-js version).

2024-11-06 10:19 UTC, nikku reviewed
@jarekdanielak Not sure how you ended up with your integration CI pattern (cf. [reference I used](https://github.com/bpmn-io/bpmn-js-token-simulation/blob/main/.github/workflows/CI.yml)).

[This should do the trick](https://github.com/bpmn-io/diagram-js-direct-editing/pull/49/commits/c0f2ea12297caa1d3fa79f14cf378249e8d61c3a) to test against different set of integration deps, cf. https://github.com/bpmn-io/diagram-js-direct-editing/actions/runs/11701527355/job/32587815880?pr=49

Let's squash the CI changes, rest looks good to me to merge.

2024-11-06 10:41 UTC, merged

2024-11-06 11:47 UTC, nikku commented
Follow-up fix: https://github.com/bpmn-io/diagram-js-direct-editing/commit/77114771245eca30ff19b62aa44f4fb1dd62ae17.